-- Generated by AutomateDV (formerly known as dbtvault)

    

WITH source_data AS (
    SELECT a.SALES_HK, a.SALES_HASHDIFF, a.LOAD_DATE, a.RECORD_SOURCE
    FROM DBT_DB.DBT_VAULT.v_stg_sales AS a
    WHERE a.SALES_HK IS NOT NULL
),

records_to_insert AS (
    SELECT DISTINCT stage.SALES_HK, stage.SALES_HASHDIFF, stage.LOAD_DATE, stage.RECORD_SOURCE
    FROM source_data AS stage
)

SELECT * FROM records_to_insert