-- Generated by AutomateDV (formerly known as dbtvault)

    

WITH source_data AS (
    SELECT a.LOCATION_HK, a.LOCATION_HASHDIFF, a.LOAD_DATE, a.RECORD_SOURCE
    FROM DBT_DB.DBT_VAULT.v_stg_location AS a
    WHERE a.LOCATION_HK IS NOT NULL
),

records_to_insert AS (
    SELECT DISTINCT stage.LOCATION_HK, stage.LOCATION_HASHDIFF, stage.LOAD_DATE, stage.RECORD_SOURCE
    FROM source_data AS stage
)

SELECT * FROM records_to_insert