












{"derived_columns": {"LOAD_DATE": "LDTS", "LOCATION_KEY": "LOCATION_ID", "RECORD_SOURCE": "SOURCE_FILE"}, "hashed_columns": {"LOCATION_HASHDIFF": {"columns": ["LOCATION_CODE", "LOCATION_ID", "LOCATION_PLANNING_CODE", "CANCELLED_FLAG", "DUMMY_FLAG", "STORE_GROUP_CODE", "CURRENCY_ID", "CONCEPT_CODE", "SELL_SQUARE_FEET", "SELL_MQ", "NOSELL_SQUARE_FEET", "NOSELL_MQ", "GROSS_STORE_SIZE", "SDB_CHANNEL_CODE", "LOCATION_SUBSUBTYPE_ID", "LOCATION_SUBSUBTYPE_CODE", "LOCATION_SUBSUBTYPE_TYPOLOGY", "LOCATION_SUBTYPE_ID", "LOCATION_SUBTYPE_CODE", "LOCATION_SUBTYPE_CODE_TYPOLOGY", "LOCATION_TYPE_ID", "LOCATION_TYPE_CODE", "LOCATION_TYPE_CODE_TYPOLOGY", "DISTRIBUTION_CHANNEL_ID", "DISTRIBUTION_CHANNEL_CODE", "DISTRIBUTION_CHANNEL_TYPOLOGY", "CITY_ID", "CITY_CODE", "STATE_ID", "STATE_CODE", "COUNTRY_ID", "COUNTRY_CODE", "DISTRICT_ID", "DISTRICT_CODE", "ZONE_ID", "ZONE_CODE", "REGION_ID", "REGION_CODE", "AREA_ID", "AREA_CODE", "MACROAREA_ID", "MACROAREA_CODE", "LOCATION_STATUS_ID", "LOCATION_STATUS_CODE", "REPORTING_UNIT_ID", "REPORTING_UNIT_CODE", "MACROZONE_ID", "MACROZONE_CODE", "CHANNEL_ID", "CHANNEL_CODE", "STORE_GROUP_PLAN_ID", "STORE_GROUP_PLAN_CODE", "STORE_GROUP_PLAN_TYPOLOGY", "CHANNEL_PLAN_ID", "CHANNEL_PLAN_CODE", "CHANNEL_PLAN_TYPOLOGY", "COUNTRY_PLAN_ID", "COUNTRY_PLAN_CODE", "LOCATION_OPENING_DATE", "LOCATION_CLOSURE_DATE", "CONSOLIDATED_FLAG_ID", "CONSOLIDATED_FLAG_CODE", "TIER_CITY_ID", "TIER_CITY_CODE", "CHANNEL_PLAN_SORT", "OPERATION_FLAG", "INSERT_DATE", "UPDATE_DATE", "__DELETE_FLAG", "__DQ_FLAG", "__DUMMY_FLAG", "DATE_PARTITION", "LDTS", "SOURCE_FILE"], "is_hashdiff": true}, "LOCATION_HK": "LOCATION_ID"}, "source_model": "TEST"}

