














-- Generated by AutomateDV (formerly known as dbtvault)

    

WITH source_data AS (

    SELECT *

    FROM DBT_DB.DBT_VAULT.raw_location
),

derived_columns AS (

    SELECT

    SOURCE_FILE AS RECORD_SOURCE,
    LOCATION_ID AS LOCATION_KEY,
    LDTS AS LOAD_DATE

    FROM source_data
),

hashed_columns AS (

    SELECT

    RECORD_SOURCE,
    LOCATION_KEY,
    LOAD_DATE,

    CAST(MD5_BINARY(NULLIF(UPPER(TRIM(CAST(LOCATION_ID AS VARCHAR))), '')) AS BINARY(16)) AS LOCATION_HK,

    CAST(MD5_BINARY() AS BINARY(16)) AS LOCATION_HASHDIFF

    FROM derived_columns
),

columns_to_select AS (

    SELECT

    RECORD_SOURCE,
    LOCATION_KEY,
    LOAD_DATE,
    LOCATION_HK,
    LOCATION_HASHDIFF

    FROM hashed_columns
)

SELECT * FROM columns_to_select