














-- Generated by AutomateDV (formerly known as dbtvault)

    

WITH source_data AS (

    SELECT *

    FROM DBT_DB.DBT_VAULT.raw_product
),

derived_columns AS (

    SELECT

    SOURCE_FILE AS RECORD_SOURCE,
    SKU_ID AS PRODUCT_KEY,
    LDTS AS LOAD_DATE

    FROM source_data
),

hashed_columns AS (

    SELECT

    RECORD_SOURCE,
    PRODUCT_KEY,
    LOAD_DATE,

    CAST(MD5_BINARY(NULLIF(UPPER(TRIM(CAST(SKU_ID AS VARCHAR))), '')) AS BINARY(16)) AS PRODUCT_HK,

    CAST(MD5_BINARY() AS BINARY(16)) AS PRODUCT_HASHDIFF

    FROM derived_columns
),

columns_to_select AS (

    SELECT

    RECORD_SOURCE,
    PRODUCT_KEY,
    LOAD_DATE,
    PRODUCT_HK,
    PRODUCT_HASHDIFF

    FROM hashed_columns
)

SELECT * FROM columns_to_select