-- Generated by AutomateDV (formerly known as dbtvault)

    

WITH row_rank_1 AS (
    SELECT rr.PRODUCT_SALES_PK, rr.PRODUCT_HK, rr.SALES_HK, rr.LOAD_DATE, rr.RECORD_SOURCE,
           ROW_NUMBER() OVER(
               PARTITION BY rr.PRODUCT_SALES_PK
               ORDER BY rr.LOAD_DATE
           ) AS row_number
    FROM DBT_DB.DBT_VAULT.v_stg_sales AS rr
    WHERE rr.PRODUCT_SALES_PK IS NOT NULL
    AND rr.PRODUCT_HK IS NOT NULL
    AND rr.SALES_HK IS NOT NULL
    QUALIFY row_number = 1
),

records_to_insert AS (
    SELECT a.PRODUCT_SALES_PK, a.PRODUCT_HK, a.SALES_HK, a.LOAD_DATE, a.RECORD_SOURCE
    FROM row_rank_1 AS a
)

SELECT * FROM records_to_insert