
  
    

        create or replace transient table DEV_DB.DBT_VAULT.hub_sales
         as
        (-- Generated by AutomateDV (formerly known as dbtvault)

    

WITH row_rank_1 AS (
    SELECT rr.SALES_HK, rr.TRANSACTION_SALES, rr.LOAD_DATE, rr.RECORD_SOURCE,
           ROW_NUMBER() OVER(
               PARTITION BY rr.SALES_HK
               ORDER BY rr.LOAD_DATE
           ) AS row_number
    FROM DEV_DB.DBT_VAULT.v_stg_sales AS rr
    WHERE rr.SALES_HK IS NOT NULL
    QUALIFY row_number = 1
),

records_to_insert AS (
    SELECT a.SALES_HK, a.TRANSACTION_SALES, a.LOAD_DATE, a.RECORD_SOURCE
    FROM row_rank_1 AS a
)

SELECT * FROM records_to_insert
        );
      
  