
  
    

        create or replace transient table DEV_DB.DBT_VAULT.hub_location
         as
        (-- Generated by AutomateDV (formerly known as dbtvault)

    

WITH row_rank_1 AS (
    SELECT rr.LOCATION_HK, rr.LOCATION_ID, rr.LOAD_DATE, rr.RECORD_SOURCE,
           ROW_NUMBER() OVER(
               PARTITION BY rr.LOCATION_HK
               ORDER BY rr.LOAD_DATE
           ) AS row_number
    FROM DEV_DB.DBT_VAULT.v_stg_location AS rr
    WHERE rr.LOCATION_HK IS NOT NULL
    QUALIFY row_number = 1
),

records_to_insert AS (
    SELECT a.LOCATION_HK, a.LOCATION_ID, a.LOAD_DATE, a.RECORD_SOURCE
    FROM row_rank_1 AS a
)

SELECT * FROM records_to_insert
        );
      
  